### ISSUE TITLE
pyaudio issue

### ISSUE THREAD

**Issue by vncntprvst** [pyacq/pyacq#105]
This may be related to Python 3.7, but there's an issue with PyAudio. The pip install fails, although it works with Conda install. However, when running `import pyacq`, I get this error: 
Could not import the PyAudio C module '_portaudio'.

**Comment by vncntprvst** [comment]
This issue is solved by install from the package with the proper bindings for PortAudio v19.
If using Conda: 'conda install -c anaconda pyaudio'

**Comment by samuelgarcia** [comment]
OK thank you for the report.
Note that I plan to write an another node that would be based on [sounddevice](https://python-sounddevice.readthedocs.io) which is another portaudio wrapper.
