### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by cimbi** [pyacq/pyacq#106]
Hi I was wondering if the project is alive. I see the tests are failing and the docs are a bit outdated. The last commit 4 months ago.

I am going to use pyacq in my project and would like to work on it (adding nodes, bug fixes, etc.). Should I create a fork or do you want me to contribute to this repository?

**Comment by samuelgarcia** [comment]
Hi.
Thank you for interest.
Yes the project is alive!! I use pyacq for allacquisition develop in my lab in Lyon.

I was not very responsive on that front last year.
I am also involved in python-neo, tridesclous and spikeinterface.
And I run out of time!!

Please make PR here I will try to include then.

**Comment by cimbi** [comment]
OK, glad to hear that! Will start creating PRs
