### ISSUE TITLE
Oscilloscope

### ISSUE THREAD

**Issue by Lx37** [pyacq/pyacq#37]
In an oscilloscope, if we set 'xsize' to a bigger value than the "buffer_length" value of the associated stream, pyacq0.1 gives us a very uggly error.

Best from Arles
Jonas&Alex

**Comment by samuelgarcia** [comment]
Oui je sais normallement c'est pas possible depuis l'UI.
self.paramGlobal.param('xsize').setLimits([2./sr, self.half_size/sr*.95])
