### ISSUE TITLE
Confusion in documentation between "sharedarray" and "sharedmem" for stream transfermode

### ISSUE THREAD

**Issue by Lx37** [pyacq/pyacq#66]
In stream.py, OutputStream configuration documentation is ambiguous concerning 'transfermode' possibilities : it say's 'sharedarray' but the key word is 'sharedmem'.
Maybe there is other places with this confusion, for example in pyacq.viewers.QTimeFreq's documentation (transfermode==sharedarray)

**Comment by samuelgarcia** [comment]
Closed by #68.
